### ISSUE TITLE
Instruction to open terminal

### ISSUE THREAD

**Issue by michellemoon236** [learn-co-curriculum/irb-readme#18]
For the "interactive Ruby Shell" lesson, in the instructions, it says the following: "Open up your terminal. (If you do not have a terminal on your computer you can use repl.it)." What a terminal is on your computer or how to open one on repl.it is not explained and so confusing. I had to use the ask a question feature to figure this out. I suggest giving more clear instructions here. For example if you use repl.it, you will need to open a new ruby file type. Then here you don't need to type "irb" as step 2 instructs. I think that is only for the terminal. In repl.it it is already in irb.

**Comment by maxwellbenton** [comment]
Hi @michellemoon236,

Thank you for opening this issue and providing feedback. We've updated the instructions to this lesson so that it is clearer what the terminal is, how to use the Sandbox terminal, and how to use repl.it (create one for Ruby, skip step 2 as Repl.it is ready to interpret Ruby) and believe this issue is resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
